### ISSUE TITLE
Some correction for GNU/Linux installation tutorial

### ISSUE THREAD

**Issue by rea987** [soulweaver91/project-carrot#68]
Shouldn't

qmake -spec=linux-clang

line become

qmake -spec linux-clang

?

Current tutorial copies 32 bit bass and bass_fx to Release folder. For x64 systems, those lines should be;

cp $BASS_DIR/x64/libbass.so .
cp $BASS_FX_DIR/x64/libbass_fx.so .

Thanks, regards.

**Comment by soulweaver91** [comment]
Yeah, it seems I've made a mistake or two while writing that quickstart guide. Just shows both how my focus is still mainly fixated on Windows and also how little traffic there is from other people :p But thanks for reporting, I'll sort this out in a moment or two :+1:
